# Task 12 🥳
We are using Jupyter in this task

In [23]:
import numpy as np

# Problem 1

**Create a 3x3 array that contains a diagonal of nines**


* in this problem we will use np.eye() to get identity matrix 

In [25]:
arr = np.eye(3,dtype = np.int64)*9
print(arr)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


# Problem 2
**Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.**


* in this problem we need first to make the array form 2 to 32 with step 2
* reshape the array to 4*4
* get mean and std for array
* make array of booleans where **mean-0.5*std <= element <= mean+0.5*std**
   


In [27]:
arr = np.arange(2,33,2).reshape(4,4)
print (arr)

mean = arr.mean()
std = arr.std()

values = arr[(arr>= (mean-.5*std))&(arr<= (mean+.5*std))]
print('\nValues are :\n')
print(values)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Values are :

[14 16 18 20]


# Problem 3
**Create a 9x9 array that contains only zero of type int.**
* in this problem first we will make array of zeros
* make the type int64

In [29]:
arr = np.zeros((9, 9), dtype=np.int64)
print (arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


# Problem 4 
**Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that
has its first column full of ones, its second column full of twos, its third column full of threes, etc.**

* First get input n
* make array of ones n*1
* multiply it to 1*n array each element has the index value ex: [1,2,3,...n]

In [31]:
n = int(input("Enter the value for n: "))
arr = np.ones((n,1),dtype = np.int64)* np.arange(1,n+1)
print (arr)

Enter the value for n:  5


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


# Problem 5
**A. Sereja and Dima**


In [34]:
import numpy as np
n = int(input().strip())
cards = np.fromstring(input().strip(), sep=' ', dtype=int)

serja=0
dima = 0
l=0
r=n-1
t=0
while l<=r:
    if cards[l] >= cards[r]:
        c = cards[l]
        l += 1
    else:
        c = cards[r]
        r -= 1
    if t==0:
        serja+=c
        t=1
    else:
        dima+=c
        t=0
print (serja, dima)

 4
 4 1 2 10


12 5


# Problem 6 
**A. Brain's Photos**

In [52]:
n, m = map(int, input().strip().split())
p=[]
c=np.array(['C', 'M', 'Y'])
for i in range(n):
    row = input().strip().split()
    p.append(row)

arr = np.array(p)
b = np.any(np.isin(arr, c))
if b:
    print("#Color")
else:
    print("#Black&White")    

 2 2
 C M
 Y  Y


#Color
